Send to epp server
elifesciences/enhanced-preprints-import pull request #39
Opened 2023-01-31 16:55 UTC by scottaubrey

2023-03-20 14:30 UTC, E-Kemp requested changes
Not sure if this is my error, docmap-ts doesn't seem to have an @types definition

The following error happened after a docker compose up
```
src/activities/parse-docmap.ts(1,10): error TS2305: Module '"@elifesciences/docmap-ts"' has no exported member 'parser'.
```

2023-04-03 08:09 UTC, nlisgo commented
> My guess would be to clear you local docker cache in case you have a cached, older version of docmap-ts library that's not being updated? Happy to pair on it if you still have problems after that.

I encountered the same issue that @E-Kemp did but removing the corresponding image and the container that was based on it, cleared that issue for me.

2023-04-03 08:39 UTC, nlisgo commented on src/activities/send-version-to-epp.ts
> +  const versionImportUri = `${config.eppServerUri}/import-version`;
This endpoint isn't working for me. I know it isn't in the master branch of server yet. I can't see a corresponding PR on server. We should aim to get this endpoint in server ahead of this.

2023-04-03 08:40 UTC, nlisgo submitted a review, later dismissed
Let's focus on introducing the `import-version` endpoint in server ahead of this.

2023-04-03 09:03 UTC, scottaubrey commented
@nlisgo said:
> Let's focus on introducing the `import-version` endpoint in server ahead of this.

The endpoint did exist already mid-January. @E-Kemp moved it in the reorg a bit back, but it's still there. This branch probably needs updating to POST to `/preprints`:

```
>  kubectl port-forward -n epp--prod deployment/epp-server 3000:3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000

<another tab> 
> curl -X POST http://localhost:3000/preprints
{"result":false,"message":"body sent failed validation: (ValidationError): \"id\" is required. \"msid\" is required. \"doi\" is required. \"versionIdentifier\" is required. \"article\" is required. \"preprintDoi\" is required. \"preprintUrl\" is required. \"preprintPosted\" is required"}

2023-04-03 14:14 UTC, nlisgo commented
I almost happy with this. Just going to do some digging around server to verify that we have all the data we need to accept the import once the validation violations are resolved.

2023-04-03 14:31 UTC, E-Kemp approved these changes

2023-04-03 14:38 UTC, merged